### PR TITLE
add sbt assembly plugin

### PR DESCRIPTION
**Pull request by vixns**

### CODE REVIEW

**Comment by vixns** [comment]
`sbt assembly` produce a fat jar, embedding all dependencies. This allow to create a simpler docker image or use an official openjdk image and grab the jar with mesos fetcher to run it.

**Comment by sauliusvl** [comment]
Sure, I understand the purpose of the plugin, but this PR effectively does nothing because `assembly` is not invoked anywhere.

I'm a bit reluctant to add this, because we already use `sbt-pack` to package jars and add them to the docker image. We specifically chose it over `sbt-assembly` because we add dependencies/app jars in separate docker layers to improve caching: https://github.com/adform/sprint/blob/master/build.sbt#L90, so I don't really buy the "simpler docker image" argument.

And as for the other argument regarding fetching it with mesos fetcher: why not just run the officially provided image? Fetching it on top of the JDK image will not work, because the native mesos library will be missing (i.e. this part: https://github.com/adform/sprint/blob/master/build.sbt#L86).

**Comment by vixns** [comment]
The official image use the mesosphere mesos packages. I prefer to avoid binary packages from commercial companies.

My base image is something like this :

```
FROM openjdk:11-jre
ENV MESOS_NATIVE_LIBRARY=/usr/lib/libmesos.so \
MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos.so
RUN \
export DEBIAN_FRONTEND=noninteractive \
&& echo "deb http://http.debian.net/debian stretch-backports contrib non-free main" >> /etc/apt/sources.list \
&& echo "deb http://http.debian.net/debian buster contrib non-free main" >> /etc/apt/sources.list \
&& apt-get update \
&& apt-get install -y libsasl2-modules libsvn1 libcurl4 curl
```
I need buster here because I'm compiling mesos from source using libcurl4-dev and openssl >= 1.1 
libsasl2-modules and libsvn1 are mesos dependencies, curl may be needed for some health checking.

Then, I'm using the fetcher to grab the `libmesos.so` from the host, the jar from a private maven repo or a trusted https source, and use a `cmd` to run it.
Or, I'm creating a custom docker image to embed the jar and the cmd, but still grab the `libmesos.so` from the host.

This way I'm sure to always use the correct libmesos.so version, compiled with a recent openssl version, and to not depend on untrusted binaries.

I like assembly because it'a just a (big) file to manage at runtime (grab / checksum / run), not a collection of various dependencies.

**Comment by sauliusvl** [comment]
OK, I get it, but still, this change does nothing as `assembly` is never invoked, so do you have a custom build pipeline, where you actually run it? 

If so, I guess adding the plugin does not hurt.

**Pull request merged**
